# Paths
#data_path: ${hydra:runtime.cwd}/data/processed
#model_save_path: ${hydra:runtime.cwd}/models/best_model.pth'

# Training Stable Parameters
batch_size: 4 # 64
n_epochs: 3
seed: 0
lr: 0.00002 #2e-5 #0.0001 
num_workers: 4
scheduler_step: 3  
accumulation_steps: 1 
wandbAPI: 80ea83cfdd37762205e46cf8ec53ce49fb040e26

#save_per_n_epochs: 1 # Save model every n epochs


#defaults:
#    - experiment: exp1