# Paths
#data_path: ${hydra:runtime.cwd}/data/processed
#model_save_path: ${hydra:runtime.cwd}/models/best_model.pth'

# Training Stable Parameters
batch_size: 8 # 64
n_epochs: 10
seed: 0
lr: 0.00002 #2e-5 #0.0001 
num_workers: 4
scheduler_step: 3  

#save_per_n_epochs: 1 # Save model every n epochs


defaults:
    - experiment: exp1