# Paths
data_path: ${hydra:runtime.cwd}/data/processed

model_save_path: ${hydra:runtime.cwd}/models

batch_size: 8 # 64
n_epochs: 10
seed: 0
lr: 0.0001
#scheduler_step: 2   # what is this 
scheduler_gamma: 0.5 #  what is this
save_per_n_epochs: 1 # Save model every n epochs


defaults:
    - experiment: exp1