wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705573005.894727
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 50
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 50
      - 53
      - 55
      - 105
      3:
      - 23
      4: 3.11.6
      5: 0.16.2
      6: 4.36.2
      8:
      - 3
      - 5
      13: windows-amd64
